### PR TITLE
Updated dependencies including React

### PR DESCRIPTION
**Pull request by AntonBazhal**
Unfortunately, update to React 15 resulted in nasty warnings while running tests. IMHO, it requires significant amount of effort to fix, thus should be addressed in a separate PR.

### CODE REVIEW

**Comment by AntonBazhal** [comment]
Ping @dlockhart

**Comment by dlockhart** [comment]
@dbatiste might be a better person to review this

**Comment by AntonBazhal** [comment]
@dlockhart, sorry, that was accidentally.

**Comment by dbatiste** [comment]
Looks good!

**Pull request merged**
